# Generated by Django 5.0.2 on 2024-02-16 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='chat_id',
        ),
        migrations.AlterField(
            model_name='user',
            name='tg_user_id',
            field=models.IntegerField(unique=True),
        ),
    ]
